package org.minekot.codegen.core

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.STRING
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class MineKotCodegenTest {
    @Test
    fun `identifier helper sanitizes names`() {
        assertEquals("Generated123BadName", mineKotIdentifier("123 bad-name"))
    }

    @Test
    fun `nullable helper toggles nullability`() {
        assertTrue(STRING.mineKotNullable().isNullable)
        assertEquals(false, STRING.mineKotNullable().mineKotNonNullable().isNullable)
    }

    @Test
    fun `object renderer emits deterministic code`() {
        val file = renderMineKotObject(
            MineKotGeneratedObject(
                packageName = "org.minekot.generated",
                name = "messages",
                kdoc = "Generated messages.",
                functions = listOf(
                    MineKotGeneratedFunction("zeta", "Returns zeta.", STRING, "z"),
                    MineKotGeneratedFunction("alpha", "Returns alpha.", STRING, "a"),
                ),
            ),
        ).toString()

        assertTrue(file.indexOf("fun alpha()") < file.indexOf("fun zeta()"))
        assertTrue(file.contains("Generated by MineKot. Do not edit."))
    }

    @Test
    fun `package and member helpers sanitize names`() {
        assertEquals("org.minekot.generated", mineKotPackageName("org.MineKot.generated"))
        assertEquals("badName", mineKotMemberIdentifier("bad-name"))
    }

    @Test
    fun `data class renderer emits deterministic properties`() {
        val file = renderMineKotDataClass(
            MineKotGeneratedDataClass(
                packageName = "org.minekot.generated",
                name = "sample config",
                kdoc = "Generated config.",
                properties = listOf(
                    MineKotGeneratedProperty("zeta", "Zeta value.", STRING),
                    MineKotGeneratedProperty("alpha", "Alpha value.", STRING),
                ),
            ),
        ).toMineKotSource()

        assertTrue(file.indexOf("val alpha") < file.indexOf("val zeta"))
        assertTrue(file.contains("data class SampleConfig"))
    }

    @Test
    fun `enum and sealed interface renderers emit stable code`() {
        val enumFile = renderMineKotEnum(
            MineKotGeneratedEnum(
                packageName = "org.minekot.generated",
                name = "mode",
                kdoc = "Generated mode.",
                constants = listOf("zeta", "alpha"),
            ),
        ).toMineKotSource()
        val sealedFile = renderMineKotSealedInterface(
            MineKotGeneratedSealedInterface(
                packageName = "org.minekot.generated",
                name = "event",
                kdoc = "Generated event.",
            ),
        ).toMineKotSource()

        assertTrue(enumFile.indexOf("ALPHA") < enumFile.indexOf("ZETA"))
        assertTrue(sealedFile.contains("sealed interface Event"))
    }

    @Test
    fun `typed expression renderer emits nested calls without source snippets`() {
        val service = MineKotKotlinName("service")
        val handler = MineKotKotlinName("handler")
        val event = MineKotKotlinName("event")
        val code = renderMineKotCode(
            listOf(
                MineKotExpressionStatement(
                    MineKotCall(
                        target = MineKotMemberAccess(MineKotReference(service), MineKotKotlinName("register")),
                        arguments = listOf(MineKotClassLiteral(ClassName("org.example", "ExampleEvent"))),
                        namedArguments = mapOf(handler to MineKotReference(event)),
                    ),
                ),
            ),
        ).toString()

        assertEquals("service.register(org.example.ExampleEvent::class, handler = event)\n", code)
    }

    @Test
    fun `typed statement renderer handles variables branches and labeled returns`() {
        val event = MineKotKotlinName("event")
        val handler = MineKotKotlinName("handler")
        val register = MineKotKotlinName("register")
        val eventType = ClassName("org.example", "ExampleEvent")
        val code = renderMineKotCode(
            listOf(
                MineKotVariable(
                    event,
                    MineKotElvis(
                        MineKotCall(MineKotReference(handler)),
                        MineKotLabeledReturn(register),
                    ),
                ),
                MineKotIf(
                    MineKotIsCheck(MineKotReference(event), eventType),
                    listOf(
                        MineKotExpressionStatement(
                            MineKotCall(MineKotReference(handler), listOf(MineKotReference(event))),
                        ),
                    ),
                ),
            ),
        ).toString()

        assertEquals(
            "val event = handler() ?: return@register\n" +
                    "if (event is org.example.ExampleEvent) {\n" +
                    "  handler(event)\n" +
                    "}\n",
            code,
        )
    }

    @Test
    fun `typed literals retain Kotlin numeric suffixes`() {
        assertEquals("0L", renderMineKotExpression(MineKotNumericLiteral(0, MineKotNumericKind.LONG)).toString())
        assertEquals("0.0f", renderMineKotExpression(MineKotNumericLiteral(0, MineKotNumericKind.FLOAT)).toString())
        assertEquals("null", renderMineKotExpression(MineKotNullLiteral).toString())
    }
}
