package org.minekot.codegen.core

import com.squareup.kotlinpoet.*

/**
 * Returns the standard generated file header.
 *
 * @return Generated file header.
 */
fun mineKotGeneratedHeader(): String =
    "Generated by MineKot. Do not edit."

/**
 * Renders a generated object model with deterministic function ordering.
 *
 * @param model Object model.
 * @return KotlinPoet file specification.
 */
fun renderMineKotObject(model: MineKotGeneratedObject): FileSpec {
    val type = TypeSpec.objectBuilder(mineKotIdentifier(model.name))
        .addKdoc(model.kdoc)
        .apply {
            model.functions.sortedBy(MineKotGeneratedFunction::name).forEach { function ->
                addFunction(
                    FunSpec.builder(function.name)
                        .addKdoc(function.kdoc)
                        .returns(function.returnType)
                        .addStatement("return %S", function.returnValue)
                        .build(),
                )
            }
        }
        .build()

    return FileSpec.builder(mineKotPackageName(model.packageName), mineKotIdentifier(model.name))
        .addFileComment(mineKotGeneratedHeader())
        .addType(type)
        .build()
}

/**
 * Renders a generated data class model with deterministic property ordering.
 *
 * @param model Data class model.
 * @return KotlinPoet file specification.
 */
fun renderMineKotDataClass(model: MineKotGeneratedDataClass): FileSpec {
    val constructor = FunSpec.constructorBuilder()
    val type = TypeSpec.classBuilder(mineKotIdentifier(model.name))
        .addModifiers(KModifier.DATA)
        .addKdoc(model.kdoc)
        .apply {
            model.properties.sortedBy(MineKotGeneratedProperty::name).forEach { property ->
                val propertyName = mineKotMemberIdentifier(property.name)
                constructor.addParameter(propertyName, property.type)
                addProperty(
                    PropertySpec.builder(propertyName, property.type)
                        .initializer(propertyName)
                        .addKdoc(property.kdoc)
                        .build(),
                )
            }
        }
        .primaryConstructor(constructor.build())
        .build()

    return FileSpec.builder(mineKotPackageName(model.packageName), mineKotIdentifier(model.name))
        .addFileComment(mineKotGeneratedHeader())
        .addType(type)
        .build()
}

/**
 * Renders a generated enum.
 *
 * @param model Enum model.
 * @return KotlinPoet file specification.
 */
fun renderMineKotEnum(model: MineKotGeneratedEnum): FileSpec {
    val type = TypeSpec.enumBuilder(mineKotIdentifier(model.name))
        .addKdoc(model.kdoc)
        .apply {
            model.constants.sorted().forEach { constant ->
                addEnumConstant(mineKotIdentifier(constant).uppercase())
            }
        }
        .build()

    return FileSpec.builder(mineKotPackageName(model.packageName), mineKotIdentifier(model.name))
        .addFileComment(mineKotGeneratedHeader())
        .addType(type)
        .build()
}

/**
 * Renders a generated sealed interface.
 *
 * @param model Sealed interface model.
 * @return KotlinPoet file specification.
 */
fun renderMineKotSealedInterface(model: MineKotGeneratedSealedInterface): FileSpec {
    val type = TypeSpec.interfaceBuilder(mineKotIdentifier(model.name))
        .addModifiers(KModifier.SEALED)
        .addKdoc(model.kdoc)
        .build()

    return FileSpec.builder(mineKotPackageName(model.packageName), mineKotIdentifier(model.name))
        .addFileComment(mineKotGeneratedHeader())
        .addType(type)
        .build()
}

/**
 * Renders a KotlinPoet file to deterministic text.
 *
 * @return Rendered source.
 */
fun FileSpec.toMineKotSource(): String =
    toString()
